[package]
name = "rustar-types"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
utoipa = "5.4.0"
utoipa-swagger-ui = "9.0.2"
uuid = { version = "1.18", features = ["v4"] }
